#!/bin/bash +xe
source './lib/pangea'
source './config'

#                            .----.       
#                            `--  ;       
#   .---.  .--.  ,-.,-. .--.  .' '  .--.  
#   : .; `' .; ; : ,. :' .; : _`,`.' .; ; 
#   : ._.'`.__,_;:_;:_;`._. ;`.__.'`.__,_;
#   : :                 .-. :             
#   :_;                 `._.'


pang3a () {
#  initialize!

#  trim

#  reference_assemble

#  filter

#  separate_unassembled

  cluster_unassembled

  exit
  generate_tables  

  count_phylogenies $tables

  make_megaclustables $tables $dir

  #run_shannon
  
  title "$(date)."
}


pang3a
