#!/bin/bash +x
set -e # script dies if anything exits in error.
# --------------------------------- USAGE -----------------------------------

# ./ribopipe.sh <directory> <database> <shannon-reads>

# - Directory contains reads
# - Database is a TaxCollector database in FASTA format
# - Shannon-reads is the number of reads to use to calculate the
#     Shannon Diversity Index

# ------------------------------ CONFIGURATION ------------------------------

cdhit_overhang="78" # Minimum CDHIT overlap
clust_min='10' # Minimum number of reads per cluster

# So you can manually specify which python/perl you want to use.
python=$(which python)
perl=$(which perl)
cores='16'

unassembled_reads="src/clc/unassembled_reads"

assemble="./src/clc/clc_ref_assemble_long"
filter="./src/clc/filter_matches"
make_tables="./src/clc/assembly_table"
cdhit="src/cdhit/cd-hit-est"

count_phyl="$python src/phylo_count.py"
megaclustable="$perl src/megaclustable.pl"
pre_shannon="$python src/preshannon.py"
shannon="$perl src/shannon.pl"
count_clusters="$python src/count_clusters.py"
label_fasta="$python src/label_fasta.py"

# To get number of cores automatically, uncomment:
#cores=`system_profiler|head -n 10|grep Total\ Number\ Of\ Cores | cut -d ':' -f 2`

# ---------------------------------------------------------------------------

dir=$1 # working directory
reads=$1/reads # where the reads are at
clc_out=$1/clc_out # where CLC's output goes
tables=$1/tables # where the tables go
database=$2 # the RDP database
shannon_reads=$3 # number of reads for Shannon-Diversity Index
run=$4 # This gets added to the headers of the unmatched reads (ugly patch)
unassembled=$1/reads/unassembled # Where unassembled reads are kept
logfile=$dir/log.txt

# ---------------------------------------------------------------------------

main () {
  title "$(date)"
  status "DIR = $dir"
  status "READS = $reads"
  status "RUN = $run"
  status "CLC_OUT = $clc_out"
  status "TABLES = $tables"
  status "DATABASE = $database"
  status "SHANNON_READS = $shannon_reads"
  status "CORES = $cores"
  status "LOGFILE = $logfile"
  
  mkdir -p $clc_out
  mkdir -p $tables
  mkdir -p $unassembled
  
#  reference_assemble
  
#  filter

  cluster_unassembled
  
  generate_tables
  
  count_phylogenies $tables
  
  make_megaclustables $tables $dir
  
#  run_shannon
  
#  title "$(date)."
 
}

cluster_unassembled () { # Cluster unassembled with cd-hit
  
  separate_unassembled
  
  cluster
  
  make_cluster_tables

}

reference_assemble () { # Run CLC Reference Assembler
  title "Assembling $reads against $database"

  for file in $reads/*.txt
  do
    status "Assembling $(basename $file) against $database"
    $assemble -o "$clc_out/$(basename $file).out" \
      -r random \
      -a global \
      -q -p fb ss 0 500 "$file" \
      -d $database \
      -l 0.5 \
      -s 0.8
  done
}

filter () { # Filters CLC assembly output based on percent similarity
  title "Filtering with $filter"
  for sim in 80 90 95 99
  do
    for file in $clc_out/*.out
    do     
      mkdir -p $clc_out/L_98_S_$sim
      status "Filtering $(basename $file) @ $sim%"
      $filter -a $file \
         -l 0.98 \
         -s .$sim \
         -o $clc_out/L_98_S_$sim/$(basename $file).filtered 
    done
  done
}

generate_tables () { # Generates CLC Tables
  title "Generating tables with $make_tables"
  for sim in 80 90 95 99
  do
    for file in $clc_out/L_98_S_$sim/*.filtered
    do
      status "$(basename $file) => $sim%"
      # Generate tables for each percent similarity
      mkdir -p $tables/L_98_S_$sim
      $make_tables \
        -n \
        -p \
        -s $file \
        > $tables/L_98_S_$sim/$(basename $file).table
    done
  done
}

separate_unassembled () { # Separates unassembled reads
  title "Separating/labelling unassembled reads"
  status "Label = $run"

  rm -rf $unassembled/L_98_S_$sim/$.fa # CLC appends :\
    

  for sim in 80 90 95 99
  do
    for file in $clc_out/L_98_S_$sim/*.filtered
    do
      status "Separating $(basename $file) @ $sim"
      # Output unassembled reads for each percent similarity

      #rm -f $unassembled/L_98_S_$sim/$(basename $file).fa # CLC appends :\
      #rm -f $unassembled/unassembled_"$sim".fa # Clean

            
      mkdir -p $unassembled/L_98_S_$sim
      $unassembled_reads \
         -p \
         -a $file \
         -o /dev/stdout | \

         # Concatenate unassembled reads while adding ids to header
         # Reads have to go together a certain way to be clustered
         # 5'-read1-3' + 3'-read2-5'
         
         $label_fasta \
           $unassembled/L_98_S_$sim/$(basename $file).fa \
           $run \
           >> $unassembled/unassembled_"$sim".fa
    done
  done
}

cluster () { # Clusters unassembled reads
  wordsize=10
  
  title "Clustering unassembled reads with $cdhit"
  status "Overhang = $cdhit_overhang"
  status "Wordsize = $wordsize"
  
  for sim in 80 90 95 99
  do
    input=$unassembled/unassembled_$sim.fa
    output=$unassembled/clustered_$sim.fa
    
    $cdhit \
      -i $input \
      -o $output \
      -c 0.$sim \
      -n $wordsize \
      -T $cores \
      -s 0.$cdhit_overhang \
      -g 1 \
      > /dev/null
      
    thismany=`grep -c '^>' $unassembled/clustered_$sim.fa`
    status "$sim% => $thismany clusters"
  done
}

make_cluster_tables () { # Makes tables similar to phylocount from clusters
  title "Building cluster tables"
  
  for sim in 80 90 95 99
  do
    file=$unassembled/clustered_$sim.fa.clstr
    status "Counting $file"
    $count_clusters $file $clust_min > $tables/clusters_$sim.txt
  done
}

count_phylogenies () { # Runs phylocount.py
  title "Summing up phylogenies with $count_phyl"
  table_dir=$1
  
  for sim in 80 90 95 99
  do
    for file in $table_dir/L_98_S_$sim/*.table
    do
      status "Counting $(basename $file) @ $sim%"
      $count_phyl $database $file
      cat $file.paired.out $file.unpaired.out > $file.both.out
     done
  done
}

make_megaclustables () { # Makes Megaclust Tables
  title "Megaclustableing with $megaclustable"
  table_dir=$1 # where they're from
  out_dir=$2 # where they go, appended to $tables

  megaclustable 99 6 species $out_dir
  megaclustable 95 5 genus $out_dir
  megaclustable 90 4 family $out_dir
  megaclustable 90 3 order $out_dir
  megaclustable 90 2 class $out_dir
  megaclustable 80 1 phylum $out_dir
  megaclustable 80 0 domain $out_dir
}


megaclustable() { # Runs megaclustable.pl
    sim=$1
    t=$2
    out=$3
    out_dir=$4

    status "Megaclustable $out: $sim%, t=$t"
    status "$tables/$out_dir/$out.txt"
    $megaclustable \
      -m $(ls -m $table_dir/L_98_S_$sim/*.both.* | tr -d ',\n') \
      -t $t \
      -o $tables/$out_dir/$out.txt
}

run_shannon () { # The shannon-diversity index
  title "Shannon Diversity Indexing"

  mkdir -p $tables/shannon/
  for sim in 80 90 95 99
  do
    mkdir -p $tables/shannon/L_98_S_$sim
    # Make files
    for file in $tables/L_98_S_$sim/*.table
    do
      $pre_shannon \
        $shannon_reads \
        $file \
        $tables/shannon/L_98_S_$sim/$(basename $file)
    done    
  done
  
  # Run Phylocount
  count_phylogenies "$tables/shannon"
  
  # Separate unassembled from smaller-tables
  
  exit
  
  
  # Run CD-HIT on unassembled reads
  
  
  unassembled="$tables/shannon/unassembled"
  
  # Run Megaclustable
  make_megaclustables "$tables/shannon" "shannon/"
  
  # Create hybrid-tables
  
  # Run shannon.pl on hybrid-tables tables
  for filename in $tables/shannon/*.txt
  do
    $shannon -t $filename >> $filename
  done
}

title () {
  purple="\033[0;35m"
  nocolor="\033[0m"
  c="$purple>>>$nocolor"
  d=">>>"
  echo -e $c $1
  echo $d $1 >> $logfile
}

status () {
  green="\033[0;36m"
  nocolor="\033[0m"
  c="[$green*$nocolor]" 
  d="[*]"
  echo -e $c $1
  echo $d $1 >> $logfile
}

main